import { useEffect, useMemo, useRef, useState } from 'react'
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { EyeSlash, Hash, TrendUp } from '@phosphor-icons/react'
import { dashboard, dashboardWindow, formatNumber, formatPercent, heatActiveLevel, heatLevel, RangeDays, TIERS } from '../analytics'
import { endDate } from '../data'
import { getMemberAvatar } from '../avatars'
import { Avatar } from '../components/Avatar'
import { DateRangePicker } from '../components/DateRangePicker'
import { metricInfo } from '../help'
import { Stat } from '../components/Stat'
import { Insight } from '../components/Insight'
import { Tabs } from '../components/Tabs'
import { CardTitle } from '../components/CardTitle'
import { ChartTooltip, LineTooltip } from '../components/ChartTooltip'
import { TierDonut } from '../components/TierDonut'
import { PageHeader } from '../components/PageHeader'
import { Card } from '../components/Card'

export interface RangeProps {
  range: RangeDays
  custom: { from: Date; to: Date } | null
  onSelectPreset: (d: RangeDays) => void
  onSelectRange: (from: Date, to: Date) => void
}


const DAY = 86400000

export function EngagementPage({ range, custom, onSelectPreset, onSelectRange }: RangeProps) {
  const [chart, setChart] = useState('Messages'), [heatMetric, setHeatMetric] = useState('Messages'), [channelMetric, setChannelMetric] = useState('Messages'), [showPeaks,setShowPeaks]=useState(true)
  const [hover, setHover] = useState<{weekday:number;hour:number;count:number;x:number;y:number}|null>(null)
  const heatRef = useRef<HTMLDivElement>(null)
  const cellsRef = useRef<HTMLDivElement>(null); const [cellW, setCellW] = useState(0); useEffect(() => { const el = cellsRef.current; if (!el) return; const measure = () => setCellW((el.clientWidth - 23 * 4) / 24); measure(); window.addEventListener('resize', measure); return () => window.removeEventListener('resize', measure) }, [])
  const hourLabel = (h:number) => h===0?'12am':h<12?`${h}am`:h===12?'12pm':`${h-12}pm`
  const heatMove = (e: React.MouseEvent, cell:{weekday:number;hour:number;count:number}) => { const r = heatRef.current?.getBoundingClientRect(); if (!r) return; setHover({...cell, x:e.clientX-r.left, y:e.clientY-r.top}) }
  const data = useMemo<ReturnType<typeof dashboardWindow>|null>(() => (custom ? dashboardWindow(custom.from, custom.to) : dashboard(range)), [range, custom])
  const d = data!
  const chartKey = chart === 'Messages' ? 'messages' : chart === 'Active members' ? 'active' : 'voice'
  const effDays = custom ? Math.max(1, Math.round((custom.to.getTime() - custom.from.getTime())/DAY)) : range
  const metricOf = (c: (typeof d.channelRows)[number]) => channelMetric === 'Messages' ? c.messages : c.active
  const channels = [...d.channelRows].sort((a,b)=>metricOf(b)-metricOf(a))
  const barMax = channels[0] ? metricOf(channels[0]) : 1
  const discussions = d.discussionRows
  const dayNames=['Mon','Tue','Wed','Thu','Fri','Sat','Sun']; const dayLabels=['Mon','Tues','Wed','Thurs','Fri','Sat','Sun']
  return <><PageHeader title="Engagement" subtitle="Understand how members participate in your community" action={<DateRangePicker range={range} custom={custom} endDate={endDate} onSelectPreset={onSelectPreset} onSelectRange={onSelectRange}/>}/>
  <div className="core-grid"><Card className="detail"><Stat label="Active members" info={metricInfo['Active members']} value={formatNumber(d.current.active)} change={{v:d.delta.active,range:effDays}} footer={<><b>{Math.round(d.current.activeRate)}%</b> of <b>{formatNumber(d.roster.inWindow)}</b> members participated in the last {effDays} day period.</>}/></Card><Card className="detail"><Stat label="New member activation" info={metricInfo['New member activation']} value={formatPercent(d.current.activation)} change={{v:d.delta.activation,pp:true,range:effDays}} footer={<><b>{formatNumber(d.activation.activated)}</b> of <b>{formatNumber(d.activation.eligible)}</b> new members activated within 7 days.</>}/></Card><Card className="detail"><Stat label="Retention" info={metricInfo['Retention']} value={formatPercent(d.current.retention)} change={{v:d.delta.retention,pp:true,range:effDays}} footer={<><b>{formatNumber(d.retention.returned)}</b> of <b>{formatNumber(d.retention.prior)}</b> members returning from the prior {effDays} days.</>}/></Card><Card className="detail"><Stat label="Messages" info={metricInfo['Messages']} value={formatNumber(d.current.messages)} change={{v:d.delta.messages,range:effDays}} footer={<><b>{formatNumber(Math.round(d.current.messages/effDays))}</b> messages per day on average over the last {effDays} days.</>}/></Card></div>
  <Card className="heat-card"><CardTitle title="Activity by day and time" action={<Tabs values={['Messages','Active members']} value={heatMetric} onChange={setHeatMetric}/>}/><div className="heat" ref={heatRef}><div className="y-labels">{dayLabels.map(x=><span key={x}>{x}</span>)}</div><div className="cells" ref={cellsRef}>{(heatMetric==='Messages'?d.heat:d.heatActive).flat().map(cell=>{ const level=heatMetric==='Messages'?heatLevel(cell.count):heatActiveLevel(cell.count); return <button type="button" key={`${cell.weekday}-${cell.hour}`} style={{background:`var(--heat-${level})`}} aria-label={`${dayLabels[cell.weekday]} ${hourLabel(cell.hour)}: ${formatNumber(cell.count)} ${heatMetric==='Messages'?'messages':'active members'}`} onMouseEnter={(e)=>heatMove(e,cell)} onMouseMove={(e)=>heatMove(e,cell)} onMouseLeave={()=>setHover(null)}/> })}<div className="hours">{Array.from({length:24},(_,i)=><span key={i}>{hourLabel(i)}</span>)}</div>{heatMetric==='Messages'&&showPeaks&&cellW>0&&d.peaks.map((b,i)=>{const left=b.minHour*(cellW+4)-2,top=b.weekday*22-2,width=(b.maxHour-b.minHour+1)*cellW+(b.maxHour-b.minHour)*4+4,height=22;return <div className="peak-range" key={i} style={{left,top,width,height}}><span className="peak-badge" tabIndex={0} role="img" aria-label={`Peak activity window: ${dayLabels[b.weekday]} ${hourLabel(b.minHour)}${b.maxHour!==b.minHour?` – ${hourLabel(b.maxHour)}`:''}`}>{i+1}<span className="tip"><span className="tip-title">Peak activity window</span><span className="tip-body">Peak activity on {b.minHour===b.maxHour?`${dayLabels[b.weekday]} ${hourLabel(b.minHour)}`:`${dayLabels[b.weekday]} ${hourLabel(b.minHour)} – ${hourLabel(b.maxHour)}`}. Averaged {b.avg.toFixed(1)} messages per hour — {b.magnitude.toFixed(1)}× the overall hourly average.</span></span></span></div>})}</div>{hover&&<span className="heat-tooltip" style={{left:Math.max(76,Math.min(hover.x,(heatRef.current?.offsetWidth??900)-76)),top:hover.y,transform:hover.y>44?'translate(-50%, calc(-100% - 10px))':'translate(-50%, 12px)'}}><ChartTooltip label={`${dayLabels[hover.weekday]} - ${hourLabel(hover.hour)}`} value={heatMetric==='Messages'?`Avg messages: ${formatNumber(hover.count)}`:`Avg active: ${formatNumber(hover.count)}`}/></span>}</div><div className="heat-footer"><div className="heat-legend"><span className="activity-legend"><span>Less activity</span><span className="heat-scale"><i/><i/><i/><i/><i/><i/><i/></span><span>More activity</span></span><span className="peak-legend"><span className="box"><i/><i/></span><span>Peak times</span></span></div><button className="peak-toggle" onClick={()=>setShowPeaks(!showPeaks)}><EyeSlash size={20}/>{showPeaks?'Hide':'Show'} peak times</button></div><Insight>Peak activity is <b>{dayNames[d.peak.weekday]} at {d.peak.hour}:00</b>, at {(d.peak.count/d.baseline).toFixed(1)}× the average hourly activity{effDays>=14?` across ${Math.floor(effDays/7)}/${Math.floor(effDays/7)} observed weeks`:''}.</Insight></Card>
  <div className="two-grid"><Card><CardTitle title="Activity over time" action={<Tabs values={['Messages','Active members','Voice participants']} value={chart} onChange={setChart}/>}/><div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={d.series}><CartesianGrid horizontal vertical={false} strokeDasharray="4 2"/><XAxis dataKey="label" tickLine={false} axisLine={{stroke:'var(--border-primary)'}} interval={Math.max(0,Math.ceil(d.series.length/9)-1)}/><YAxis tickLine={false} axisLine={false} width={30} tickFormatter={(v)=>v>=1000?`${v/1000}K`:String(v)}/><Tooltip content={<LineTooltip metric={chart==='Messages'?'Messages':'Members'}/>}/><Line type="linear" dataKey={chartKey} stroke="var(--content-brand)" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div></Card>
  <Card><CardTitle title="Participation by activity level" meta="Trailing 28 days"/><TierDonut tiers={d.tiers}/></Card></div>
  <Card className="metrics"><CardTitle title="Engagement depth" className="metrics-title"/><div className="metric-row"><div className="metric"><Stat layout="below" label="Reply rate" info={metricInfo['Reply rate']} value={formatPercent(d.current.replyRate)} change={{v:d.delta.replyRate,pp:true,range,caption:'vs last period'}}/></div><div className="metric"><Stat layout="below" label="Reaction rate" info={metricInfo['Reaction rate']} value={formatPercent(d.current.reactionRate)} change={{v:d.delta.reactionRate,pp:true,range,caption:'vs last period'}}/></div><div className="metric"><Stat layout="below" label="Voice participants" info={metricInfo['Voice participants']} value={formatNumber(d.current.voice)} change={{v:d.delta.voice,range,caption:'vs last period'}}/></div><div className="metric"><Stat layout="below" label="Total voice time" info={metricInfo['Total voice time']} value={`${formatNumber(Math.round(d.current.voiceMinutes/60))}h`} change={{v:d.delta.voiceMinutes,range,caption:'vs last period'}}/></div></div><div className="metrics-insight"><Insight><b>{Math.round(d.current.voiceOnly/d.current.active*100)}%</b> of active members participated only in voice calls this period.</Insight></div></Card>
  <div className="bottom-grid"><Card><CardTitle title="Most active channels" action={<Tabs values={['Messages','Active members']} value={channelMetric} onChange={setChannelMetric}/>}/><div className="table-head"><span>Channel name</span><span>{channelMetric}</span></div>{channels.slice(0,5).map((x,i)=><div className="channel-row" key={x.id}><span className="inf-rank">{i+1}</span><span className="channel-stats"><span className="channel-name"><Hash size={20}/>{x.name}</span><span className="channel-bar-row"><span className="bar"><i style={{width:`${metricOf(x)/barMax*100}%`}}/></span><span className="channel-count">{formatNumber(metricOf(x))}</span></span></span></div>)}</Card>
  <Card><CardTitle title="Trending discussions"/>{discussions.slice(0,4).map(x=><div className="discussion" key={x.id}><span className="tag"><Hash size={20}/>{x.channel}</span><div><p>{x.text}</p><div className="discussion-meta"><span className="meta-avatars"><span className="avatar-stack" title={`${x.participants} participants`}>{x.avatars.slice(0,3).map((m,i)=><span className="avatar-slot" key={m.id} style={{zIndex:i}}><Avatar spec={getMemberAvatar(m.id)} name={m.name}/></span>)}</span>{x.participants>3&&<em className="avatar-others">+{x.participants-3} others</em>}</span><span className="stat"><b>{formatNumber(x.replies)}</b> Replies</span><span className="stat"><b>{formatNumber(x.reactions)}</b> Reactions</span><strong><TrendUp size={12}/>{x.score.toFixed(1)}×<small> usual activity</small></strong></div></div></div>)}</Card></div>
  </>
}
