import { channels, conversations, endDate, members, messages, voiceSessions } from './data'
export type RangeDays = 7 | 14 | 30 | 90
const day = 86400000; const unique = <T,>(items: T[]) => new Set(items)
export const formatNumber = (value: number) => new Intl.NumberFormat('en-US', { notation: value > 9999 ? 'compact' : 'standard', maximumFractionDigits: 1 }).format(value)
export const formatPercent = (value: number) => `${Math.round(value)}%`
const activeIds = (start: Date, end: Date) => unique([...messages.filter(x => x.at >= start && x.at <= end).flatMap(x => [x.memberId, ...x.reactorIds]), ...voiceSessions.filter(x => x.at >= start && x.at <= end).map(x => x.memberId)])
export function dashboard(days: RangeDays) {
  const end = endDate, start = new Date(end.getTime() - days * day), previousStart = new Date(start.getTime() - days * day)
  const periodMessages = messages.filter(x => x.at >= start && x.at <= end), periodVoice = voiceSessions.filter(x => x.at >= start && x.at <= end), active = activeIds(start, end), prior = activeIds(previousStart, start)
  const eligible = members.filter(m => !m.bot && m.joinedAt >= start && m.joinedAt <= new Date(end.getTime() - 7 * day)); const activated = eligible.filter(m => activeIds(m.joinedAt, new Date(m.joinedAt.getTime() + 7 * day)).has(m.id)).length
  const eligiblePrior = members.filter(m => !m.bot && m.joinedAt >= previousStart && m.joinedAt <= new Date(start.getTime() - 7 * day)); const activatedPrior = eligiblePrior.filter(m => activeIds(m.joinedAt, new Date(m.joinedAt.getTime() + 7 * day)).has(m.id)).length
  const prior2 = activeIds(new Date(previousStart.getTime() - days * day), previousStart)
  const voiceIds = unique(periodVoice.map(x => x.memberId)), messageIds = unique(periodMessages.map(x => x.memberId)), totalMembers = members.filter(x => !x.bot).length
  const activeRate = active.size / totalMembers * 100, priorRate = prior.size / totalMembers * 100, activationRate = eligible.length ? activated / eligible.length * 100 : 0, priorActivation = eligiblePrior.length ? activatedPrior / eligiblePrior.length * 100 : 0, retentionRate = prior.size ? [...prior].filter(id => active.has(id)).length / prior.size * 100 : 0, priorRetention = prior2.size ? [...prior2].filter(id => prior.has(id)).length / prior2.size * 100 : retentionRate, returned = [...prior].filter(id => active.has(id)).length
  const current = { active: active.size, activeRate, activation: activationRate, retention: retentionRate, messages: periodMessages.length, replyRate: periodMessages.filter(x => x.hasReply).length / Math.max(1, periodMessages.length) * 100, reactionRate: periodMessages.filter(x => x.reactions > 0).length / Math.max(1, periodMessages.length) * 100, voice: voiceIds.size, voiceMinutes: periodVoice.reduce((n, x) => n + x.minutes, 0), voiceOnly: [...voiceIds].filter(x => !messageIds.has(x)).length }
  const visibleDays = Math.min(days, 30); const series = Array.from({ length: visibleDays }, (_, i) => { const s = new Date(end.getTime() - (visibleDays - 1 - i) * day), e = new Date(s.getTime() + day), rows = periodMessages.filter(x => x.at >= s && x.at < e); return { label: `${s.getUTCMonth()+1}/${s.getUTCDate()}`, messages: rows.length, active: activeIds(s, e).size, voice: unique(periodVoice.filter(x => x.at >= s && x.at < e).map(x => x.memberId)).size } })
  const cutoff = new Date(end.getTime() - 28 * day); const scored = members.filter(m => !m.bot).map(m => { const own = messages.filter(x => x.memberId === m.id && x.at >= cutoff), voice = voiceSessions.filter(x => x.memberId === m.id && x.at >= cutoff), activeDays = unique([...own.map(x => x.at.toDateString()), ...voice.map(x => x.at.toDateString())]).size, breadth = unique(own.map(x => x.channelId)).size, interactions = own.reduce((n,x) => n + (x.hasReply ? 1 : 0) + x.reactions, 0); return { ...m, activeDays, score: activeDays * .5 + Math.log1p(own.length) * 2 + Math.log1p(interactions) + breadth } }).sort((a,b)=>b.score-a.score)
  const actives = scored.filter(x => x.activeDays > 0); const tiers = ['Superuser','Contributor','Regular','Lurker','Inactive'].map(tier => ({ tier, value: scored.filter((m,i) => (!m.activeDays ? 'Inactive' : i < Math.ceil(actives.length*.05) ? 'Superuser' : i < Math.ceil(actives.length*.2) ? 'Contributor' : m.activeDays >= 5 ? 'Regular' : 'Lurker') === tier).length }))
  const heat = Array.from({ length: 7 }, (_, weekday) => Array.from({ length: 24 }, (_, hour) => ({ weekday, hour, count: periodMessages.filter(x => x.at.getUTCDay() === (weekday + 1) % 7 && x.at.getUTCHours() === hour).length / Math.max(1, days / 7) })))
  const peak = heat.flat().reduce((a,b) => a.count > b.count ? a : b); const baseline = periodMessages.length / Math.max(1, days * 24)
  const channelRows = channels.map(c => ({ ...c, messages: periodMessages.filter(x => x.channelId === c.id).length, active: unique(periodMessages.filter(x => x.channelId === c.id).map(x => x.memberId)).size })).sort((a,b)=>b.messages-a.messages)
  const discussionRows = conversations.map(c => { const items = periodMessages.filter(x => x.conversationId === c.id), recent = items.filter(x => x.at >= new Date(end.getTime()-3*3600000)), priorItems = items.filter(x => x.at >= new Date(end.getTime()-27*3600000) && x.at < new Date(end.getTime()-3*3600000)), velocity = recent.reduce((n,x)=>n+(x.hasReply?1:0)+x.reactions*.5,0)+unique(recent.map(x=>x.memberId)).size, baseline = (priorItems.reduce((n,x)=>n+(x.hasReply?1:0)+x.reactions*.5,0)+unique(priorItems.map(x=>x.memberId)).size)/8, avatars = [...recent].sort((a,b)=>b.at.getTime()-a.at.getTime()).reduce((map,x)=>map.has(x.memberId)?map:map.set(x.memberId,(members.find(m=>m.id===x.memberId)?.name ?? x.memberId)),new Map<string,string>()); return { ...c, channel: channels.find(x=>x.id===c.channelId)!.name, replies: recent.filter(x=>x.hasReply).length, reactions: recent.reduce((n,x)=>n+x.reactions,0), participants: unique(recent.map(x=>x.memberId)).size, avatars: [...avatars].slice(0,3).map(([id,name])=>({id,name})), score: velocity / (baseline || 1) } }).sort((a,b)=>b.score-a.score)
  const delta = { active: prior.size ? (active.size - prior.size) / prior.size * 100 : 0, activeRate: activeRate - priorRate, activation: activationRate - priorActivation, retention: retentionRate - priorRetention }
  return { start, end, current, delta, activation: { activated, eligible: eligible.length }, retention: { returned, prior: prior.size }, series, tiers, heat, peak, baseline, channelRows, discussionRows }
}
