import { useMemo, useRef, useState } from 'react'
import { CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { CalendarBlank, CaretDown, CaretUpDown, ChartBar, EyeSlash, Gear, Graph, Hash, Headset, House, Info, Lightning, SidebarSimple, TrendUp, Users } from '@phosphor-icons/react'
import MithrilIcon from './assets/mithril-icon.svg'
import MithrilWordmark from './assets/mithril-wordmark.svg'
import { dashboard, formatNumber, formatPercent, RangeDays } from './analytics'
import { Stat } from './components/Stat'
import { Insight } from './components/Insight'
import { Tabs } from './components/Tabs'
import { CardTitle } from './components/CardTitle'
import { ChartTooltip, DonutTooltip, LineTooltip } from './components/ChartTooltip'

const tiers = ['Superuser','Contributor','Regular','Lurker','Inactive']
const colors: Record<string,string> = { Superuser:'var(--chart-superuser)', Contributor:'var(--chart-contributor)', Regular:'var(--chart-regular)', Lurker:'var(--chart-lurker)', Inactive:'var(--chart-inactive)' }
const days: RangeDays[] = [7,14,30,90]
function Card({ children, className='' }: {children: React.ReactNode; className?: string}) { return <section className={`card ${className}`}>{children}</section> }
const avatarPalette = ['#693CF3','#009A47','#008EFF','#FDAB00','#3CAA9F','#E5484D']
const avatarColor = (id:string) => avatarPalette[[...id].reduce((n,c)=>n+c.charCodeAt(0),0)%avatarPalette.length]
export default function App() {
  const [range, setRange] = useState<RangeDays>(30), [chart, setChart] = useState('Messages'), [heatMetric, setHeatMetric] = useState('Messages'), [channelMetric, setChannelMetric] = useState('Messages'), [showPeaks,setShowPeaks]=useState(true)
  const [hover, setHover] = useState<{weekday:number;hour:number;count:number;x:number;y:number}|null>(null)
  const heatRef = useRef<HTMLDivElement>(null)
  const hourLabel = (h:number) => h===0?'12am':h<12?`${h}am`:h===12?'12pm':`${h-12}pm`
  const heatMove = (e: React.MouseEvent, cell:{weekday:number;hour:number;count:number}) => { const r = heatRef.current?.getBoundingClientRect(); if (!r) return; setHover({...cell, x:e.clientX-r.left, y:e.clientY-r.top}) }
  const data = useMemo(()=>dashboard(range),[range]); const chartKey = chart === 'Messages' ? 'messages' : chart === 'Active members' ? 'active' : 'voice'
  const metricOf = (c: (typeof data.channelRows)[number]) => channelMetric === 'Messages' ? c.messages : c.active
  const channels = [...data.channelRows].sort((a,b)=>metricOf(b)-metricOf(a))
  const total = channelMetric === 'Messages' ? data.current.messages : data.current.active
  const discussions = data.discussionRows
  const maxHeat = Math.max(...data.heat.flat().map(x=>x.count)); const dayNames=['Mon','Tue','Wed','Thu','Fri','Sat','Sun']; const dayLabels=['Mon','Tues','Wed','Thurs','Fri','Sat','Sun']
  const navigation = [{label:'Overview',icon:House},{label:'Engagement',icon:ChartBar},{label:'Relationships',icon:Graph},{label:'People',icon:Users}]
  return <div className="app"><aside><div className="community-switch"><div className="community-switch-inner"><div className="community-info"><div className="community-avatar">G</div><span>Gitcoin</span></div><CaretUpDown size={16}/></div></div><nav>{navigation.map(({label,icon:Icon})=><button className={label==='Engagement'?'active':''} key={label}><Icon size={20}/>{label}</button>)}</nav><div className="side-bottom"><div className="bottom-icons"><button><Gear size={20}/>Settings</button><button><Info size={20}/>Help</button><button><Headset size={20}/>Support</button></div><div className="trial"><div className="trial-card"><small>Trial ends in 10 days</small><button className="upgrade"><Lightning weight="fill" size={20}/>Upgrade to Pro</button></div></div><hr/><div className="logo-row"><div className="logo-inner"><div className="brand"><img src={MithrilIcon} alt=""/><img src={MithrilWordmark} alt="Mithril"/></div><SidebarSimple size={20}/></div></div></div></aside>
  <main><header><div><h1>Engagement</h1><p>Understand how members participate in your community</p></div><div className="date-control"><span className="dc-cal"><CalendarBlank size={16}/></span><span className="dc-value">Last {range} Days</span><span className="dc-caret"><CaretDown size={16}/></span><select className="dc-select" aria-label="Reporting period" value={range} onChange={e=>setRange(Number(e.target.value) as RangeDays)}>{days.map(x=><option value={x} key={x}>Last {x} Days</option>)}</select></div></header>
  <div className="core-grid"><Card className="detail"><Stat label="Active members" value={formatNumber(data.current.active)} change={{v:data.delta.active,range}} footer={<><b>{Math.round(data.current.activeRate)}%</b> of <b>{formatNumber(data.totalMembers)}</b> members participated in the last {range} day period.</>}/></Card><Card className="detail"><Stat label="New member activation" value={formatPercent(data.current.activation)} change={{v:data.delta.activation,pp:true,range}} footer={<><b>{formatNumber(data.activation.activated)}</b> of <b>{formatNumber(data.activation.eligible)}</b> new members activated within 7 days.</>}/></Card><Card className="detail"><Stat label="Retention" value={formatPercent(data.current.retention)} change={{v:data.delta.retention,pp:true,range}} footer={<><b>{formatNumber(data.retention.returned)}</b> of <b>{formatNumber(data.retention.prior)}</b> members returning from the prior {range} days.</>}/></Card><Card className="detail"><Stat label="Messages" value={formatNumber(data.current.messages)} change={{v:15,range}} footer={<><b>{Math.round(data.current.messages/range)}</b> messages per day on average over the last {range} days.</>}/></Card></div>
  <div className="two-grid"><Card><CardTitle title="Activity over time" action={<Tabs values={['Messages','Active members','Voice participants']} value={chart} onChange={setChart}/>}/><div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.series}><CartesianGrid horizontal vertical={false} strokeDasharray="4 2"/><XAxis dataKey="label" tickLine={false} axisLine={false} interval={Math.max(0,Math.ceil(data.series.length/9)-1)}/><YAxis tickLine={false} axisLine={false} width={30} tickFormatter={(v)=>v>=1000?`${v/1000}K`:String(v)}/><Tooltip content={<LineTooltip metric={chart==='Messages'?'Messages':'Members'}/>}/><Line type="linear" dataKey={chartKey} stroke="var(--content-brand)" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div></Card>
  <Card><CardTitle title="Participation by activity level"/><div className="donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.tiers} dataKey="value" nameKey="tier" innerRadius={63} outerRadius={77} paddingAngle={2}>{data.tiers.map(x=><Cell key={x.tier} fill={colors[x.tier]}/>)}</Pie><Tooltip content={<DonutTooltip/>}/></PieChart></ResponsiveContainer><div className="total"><b>{formatNumber(data.tiers.reduce((s,t)=>s+t.value,0))}</b><span>Members</span></div></div><div className="legend"><div className="legend-col">{data.tiers.slice(0,3).map(x=><div className="legend-item" key={x.tier}><span className="label"><i style={{background:colors[x.tier]}}/><span>{x.tier}</span></span><span className="count"><b>{formatPercent(x.value/data.tiers.reduce((s,t)=>s+t.value,0)*100)}</b><em>({formatNumber(x.value)})</em></span></div>)}</div><div className="legend-col">{data.tiers.slice(3).map(x=><div className="legend-item" key={x.tier}><span className="label"><i style={{background:colors[x.tier]}}/><span>{x.tier}</span></span><span className="count"><b>{formatPercent(x.value/data.tiers.reduce((s,t)=>s+t.value,0)*100)}</b><em>({formatNumber(x.value)})</em></span></div>)}</div></div></Card></div>
  <Card className="metrics"><CardTitle title="Engagement depth" className="metrics-title"/><div className="metric-row"><div className="metric"><Stat layout="below" label="Reply rate" value={formatPercent(data.current.replyRate)} change={{v:4,range,caption:'vs last period'}}/></div><div className="metric"><Stat layout="below" label="Reaction rate" value={formatPercent(data.current.reactionRate)} change={{v:6,range,caption:'vs last period'}}/></div><div className="metric"><Stat layout="below" label="Voice participants" value={formatNumber(data.current.voice)} change={{v:15,range,caption:'vs last period'}}/></div><div className="metric"><Stat layout="below" label="Total voice time" value={`${Math.round(data.current.voiceMinutes/60)}h`} change={{v:15,range,caption:'vs last period'}}/></div></div><div className="metrics-insight"><Insight><b>{Math.round(data.current.voiceOnly/data.current.active*100)}%</b> of active members participated only in voice calls this period.</Insight></div></Card>
  <Card className="heat-card"><CardTitle title="Activity by day and time" action={<Tabs values={['Messages','Active members']} value={heatMetric} onChange={setHeatMetric}/>}/><div className="heat" ref={heatRef}><div className="y-labels">{dayLabels.map(x=><span key={x}>{x}</span>)}</div><div className="cells">{data.heat.flat().map(cell=>{ const level=Math.min(7,Math.max(1,Math.ceil((maxHeat?cell.count/maxHeat:0)*7))); return <button key={`${cell.weekday}-${cell.hour}`} style={{background:`var(--heat-${level})`}} onMouseEnter={(e)=>heatMove(e,cell)} onMouseMove={(e)=>heatMove(e,cell)} onMouseLeave={()=>setHover(null)}/> })}<div className="hours">{Array.from({length:24},(_,i)=><span key={i}>{hourLabel(i)}</span>)}</div>{showPeaks&&data.peaks.map((p,i)=><div className="peak-overlay" key={i} style={{top:p.weekday*22,left:`${p.hour*(100/24)}%`}}><b>{i+1}</b></div>)}</div>{hover&&<span className="heat-tooltip" style={{left:Math.max(76,Math.min(hover.x,(heatRef.current?.offsetWidth??900)-76)),top:hover.y,transform:hover.y>44?'translate(-50%, calc(-100% - 10px))':'translate(-50%, 12px)'}}><ChartTooltip label={`${dayLabels[hover.weekday]} - ${hourLabel(hover.hour)}`} value={`Messages: ${formatNumber(hover.count)}`}/></span>}</div><div className="heat-footer"><div className="heat-legend"><span className="activity-legend"><span>Less activity</span><span className="heat-scale"><i/><i/><i/><i/><i/><i/><i/></span><span>More activity</span></span><span className="peak-legend"><span className="box"><i/><i/></span><span>Peak times</span></span></div><button className="peak-toggle" onClick={()=>setShowPeaks(!showPeaks)}><EyeSlash size={20}/>{showPeaks?'Hide':'Show'} peak times</button></div><Insight>Peak activity is <b>{dayNames[data.peak.weekday]} at {data.peak.hour}:00</b>, at {(data.peak.count/data.baseline).toFixed(1)}× the average hourly activity{range>=14?` across ${Math.floor(range/7)}/${Math.floor(range/7)} observed weeks`:''}.</Insight></Card>
  <div className="bottom-grid"><Card><CardTitle title="Most active channels" action={<Tabs values={['Messages','Active members']} value={channelMetric} onChange={setChannelMetric}/>}/><div className="table-head"><span>Channel name</span><span>{channelMetric}</span></div>{channels.slice(0,6).map((x,i)=><div className="channel-row" key={x.id}><span className="rank">{i+1}</span><span className="channel-stats"><span className="channel-details"><span className="channel-name"><Hash size={20}/>{x.name}</span><span className="channel-count"><b>{formatNumber(metricOf(x))}</b><em>({formatPercent(metricOf(x)/total*100)})</em></span></span><span className="bar"><i style={{width:`${metricOf(x)/total*100}%`}}/></span></span></div>)}<button className="view">View all channels →</button></Card>
  <Card><CardTitle title="Trending discussions"/>{discussions.slice(0,4).map(x=><div className="discussion" key={x.id}><span className="tag"><Hash size={20}/>{x.channel}</span><div><p>{x.text}</p><div className="discussion-meta"><span className="meta-avatars"><span className="avatar-stack" title={`${x.participants} participants`}>{x.avatars.slice(0,3).map((m,i)=><i key={m.id} style={{background:avatarColor(m.id),zIndex:i}}>{m.name.charAt(0).toUpperCase()}</i>)}</span>{x.participants>3&&<em className="avatar-others">+{x.participants-3} others</em>}</span><span className="stat"><b>{formatNumber(x.replies)}</b> Replies</span><span className="stat"><b>{formatNumber(x.reactions)}</b> Reactions</span><strong><TrendUp size={12}/>{x.score.toFixed(1)}×<small> usual activity</small></strong></div></div></div>)}</Card></div>
  </main></div>
}
