import { useMemo, useState } from 'react'
import { Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { CalendarBlank, CaretDown, CaretUp, CaretUpDown, ChatCircle, Gear, Graph, Headset, House, Info, SidebarSimple, SketchLogo, TrendDown, TrendUp, Users } from '@phosphor-icons/react'
import MithrilIcon from './assets/mithril-icon.svg'
import MithrilWordmark from './assets/mithril-wordmark.svg'
import { dashboard, formatNumber, formatPercent, RangeDays } from './analytics'
import { Label } from './components/Label'

const tiers = ['Superuser','Contributor','Regular','Lurker','Inactive']
const colors: Record<string,string> = { Superuser:'#693CF3', Contributor:'#42BB00', Regular:'#008EFF', Lurker:'#FDAB00', Inactive:'#3CAA9F' }
const days: RangeDays[] = [7,14,30,90]
const dateText = (date: Date) => date.toLocaleDateString('en-US',{month:'short',day:'numeric'})
function Card({ children, className='' }: {children: React.ReactNode; className?: string}) { return <section className={`card ${className}`}>{children}</section> }
function Tabs({ values, value, onChange }: {values:string[];value:string;onChange:(x:string)=>void}) { return <div className="tabs">{values.map(x=><button key={x} className={value===x?'selected':''} onClick={()=>onChange(x)}>{x}</button>)}</div> }
function Metric({ label, value, detail, good=true }: {label:string;value:string;detail:string;good?:boolean}) { return <div className="metric"><Label text={label}/><strong>{value}</strong><small className={good?'positive':''}>{good?<TrendUp size={12}/>:<TrendDown size={12}/>}{detail}</small></div> }
function Sparkline({ data, color }: {data:{value:number}[];color:string}) { return <div className="sparkline"><ResponsiveContainer width="100%" height="100%"><LineChart data={data}><Line dataKey="value" type="monotone" stroke={color} strokeWidth={1.5} dot={false}/></LineChart></ResponsiveContainer></div> }
function Change({ v, pp=false, range }: {v:number;pp?:boolean;range:number}) { const up = v >= 0, n = Math.round(Math.abs(v)); return <span className={`metric-change ${up?'positive':'negative'}`}><b>{up?<CaretUp size={12}/>:<CaretDown size={12}/>}{n}{pp?'pp':'%'}</b><em>vs last {range}D</em></span> }
export default function App() {
  const [range, setRange] = useState<RangeDays>(30), [chart, setChart] = useState('Messages'), [heatMetric, setHeatMetric] = useState('Messages'), [query, setQuery] = useState(''), [sort, setSort] = useState<'messages'|'active'>('messages'), [showPeaks,setShowPeaks]=useState(true)
  const data = useMemo(()=>dashboard(range),[range]); const chartKey = chart === 'Messages' ? 'messages' : chart === 'Active members' ? 'active' : 'voice'
  const channels = [...data.channelRows].sort((a,b)=>sort==='messages'?b.messages-a.messages:b.active-a.active).filter(x=>x.name.includes(query.toLowerCase()))
  const discussions = data.discussionRows.filter(x=>x.text.toLowerCase().includes(query.toLowerCase()))
  const maxHeat = Math.max(...data.heat.flat().map(x=>x.count)); const dayNames=['Mon','Tue','Wed','Thu','Fri','Sat','Sun']
  const navigation = [{label:'Overview',icon:House},{label:'Engagement',icon:ChatCircle},{label:'Relationships',icon:Graph},{label:'People',icon:Users}]
  const activeSpark = data.series.map(x=>({value:x.active})), rateSpark = data.series.map(x=>({value:x.active / 1240 * 100}))
  return <div className="app"><aside><div className="community-switch"><div className="community-switch-inner"><div className="community-info"><div className="community-avatar">G</div><span>Gitcoin</span></div><CaretUpDown size={16}/></div></div><nav>{navigation.map(({label,icon:Icon})=><button className={label==='Engagement'?'active':''} key={label}><Icon size={20}/>{label}</button>)}</nav><div className="side-bottom"><div className="bottom-icons"><button><Gear size={20}/>Settings</button><button><Info size={20}/>Help</button><button><Headset size={20}/>Support</button></div><div className="trial"><div className="trial-card"><small>Trial ends in 10 days</small><button className="upgrade"><SketchLogo size={20}/>Upgrade to Pro</button></div></div><hr/><div className="logo-row"><div className="logo-inner"><div className="brand"><img src={MithrilIcon} alt=""/><img src={MithrilWordmark} alt="Mithril"/></div><SidebarSimple size={20}/></div></div></div></aside>
  <main><header><div><h1>Engagement</h1><p>Understand how members participate in your community</p></div><div className="date-control"><CalendarBlank size={16}/><select value={range} onChange={e=>setRange(Number(e.target.value) as RangeDays)}>{days.map(x=><option value={x} key={x}>Last {x} days</option>)}</select><b>{dateText(data.start)} – {dateText(data.end)}</b></div></header>
  <div className="core-grid"><Card><div className="stat"><Label text="Active members" info={false}/><div className="stat-row"><h2>{formatNumber(data.current.active)}</h2><Change v={data.delta.active} range={range}/></div></div><Sparkline data={activeSpark} color="#693CF3"/></Card><Card><div className="stat"><Label text="Active member rate"/><div className="stat-row"><h2>{formatPercent(data.current.activeRate)}</h2><Change v={data.delta.activeRate} pp range={range}/></div></div><Sparkline data={rateSpark} color="#009A47"/></Card><Card><div className="stat"><Label text="New member activation"/><div className="stat-row"><h2>{formatPercent(data.current.activation)}</h2><Change v={data.delta.activation} pp range={range}/></div></div><p className="stat-info"><b>{formatNumber(data.activation.activated)}</b> of <b>{formatNumber(data.activation.eligible)}</b> new members activated within 7 days.</p></Card><Card><div className="stat"><Label text="Retention"/><div className="stat-row"><h2>{formatPercent(data.current.retention)}</h2><Change v={data.delta.retention} pp range={range}/></div></div><p className="stat-info"><b>{formatNumber(data.retention.returned)}</b> of <b>{formatNumber(data.retention.prior)}</b> members returning from the prior {range} days.</p></Card></div>
  <Card className="metrics"><div className="metric-row"><Metric label="Messages" value={formatNumber(data.current.messages)} detail="15% vs last period"/><Metric label="Reply rate" value={formatPercent(data.current.replyRate)} detail="4% vs last period"/><Metric label="Reaction rate" value={formatPercent(data.current.reactionRate)} detail="6% vs last period"/><Metric label="Voice participants" value={formatNumber(data.current.voice)} detail="15% vs last period"/><Metric label="Total voice time" value={`${Math.round(data.current.voiceMinutes/60)}h`} detail="15% vs last period" good={false}/></div><div className="insight">✦ <span><b>{Math.round(data.current.voiceOnly/data.current.active*100)}%</b> of active members participated only in voice calls this period.</span></div></Card>
  <div className="two-grid"><Card><h3>Activity over time</h3><Tabs values={['Messages','Active members','Voice participants']} value={chart} onChange={setChart}/><div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.series}><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{fontSize:'0.625rem',fill:'#8E96A4'}} interval="preserveStartEnd"/><YAxis tickLine={false} axisLine={false} tick={{fontSize:'0.625rem',fill:'#8E96A4'}} width={30}/><Tooltip/><Line type="monotone" dataKey={chartKey} stroke="#693CF3" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div></Card>
  <Card><h3>Participation by activity level</h3><div className="donut"><ResponsiveContainer width="100%" height={170}><PieChart><Pie data={data.tiers} dataKey="value" nameKey="tier" innerRadius={52} outerRadius={77} paddingAngle={2}>{data.tiers.map(x=><Cell key={x.tier} fill={colors[x.tier]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="total"><b>{formatNumber(1247)}</b><span>Members</span></div></div><div className="legend">{data.tiers.map(x=><span key={x.tier}><i style={{background:colors[x.tier]}}/>{x.tier} <b>{formatPercent(x.value/data.tiers.reduce((s,t)=>s+t.value,0)*100)}</b></span>)}</div></Card></div>
  <Card className="heat-card"><div className="heat-header"><h3>Activity by day and time</h3><Tabs values={['Messages','Active members']} value={heatMetric} onChange={setHeatMetric}/></div><div className="heat"><div className="y-labels">{dayNames.map(x=><span key={x}>{x}</span>)}</div><div className="cells">{data.heat.flat().map(cell=>{ const intensity=Math.max(.1,cell.count/maxHeat); const peak=cell.weekday===data.peak.weekday&&cell.hour===data.peak.hour; return <button title={`${dayNames[cell.weekday]} ${cell.hour}:00 — ${cell.count.toFixed(1)} average messages`} key={`${cell.weekday}-${cell.hour}`} className={peak&&showPeaks?'peak':''} style={{background:`rgba(0,154,71,${.12+.8*intensity})`}}/> })}<div className="hours">{Array.from({length:24},(_,i)=><span key={i}>{i%3===0?(i===0?'12a':i<12?`${i}a`:i===12?'12p':`${i-12}p`):''}</span>)}</div></div></div><div className="heat-footer"><span>Less activity <i/> <i/> <i/> <i/> More activity</span><button onClick={()=>setShowPeaks(!showPeaks)}>{showPeaks?'Hide':'Show'} peak times</button></div><div className="insight">✦ Peak activity is <b>{dayNames[data.peak.weekday]} at {data.peak.hour}:00</b>, at {(data.peak.count/data.baseline).toFixed(1)}× the average hourly activity{range>=14?` across ${Math.floor(range/7)}/${Math.floor(range/7)} observed weeks`:''}.</div></Card>
  <div className="bottom-grid"><Card><div className="table-title"><h3>Most active channels</h3><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search"/></div><div className="table-head"><span>CHANNEL NAME</span><button onClick={()=>setSort('messages')}>MESSAGES {sort==='messages'?'↓':''}</button><button onClick={()=>setSort('active')}>ACTIVE {sort==='active'?'↓':''}</button></div>{channels.slice(0,6).map(x=><div className="channel-row" key={x.id}><span># {x.name}</span><b>{formatNumber(x.messages)}</b><small>{x.active}</small></div>)}<button className="view">View all channels →</button></Card>
  <Card><div className="table-title"><h3>Trending discussions</h3></div>{discussions.slice(0,4).map(x=><div className="discussion" key={x.id}><span className="tag"># {x.channel}</span><div><p>{x.text}</p><small><b>{x.participants}</b> participants &nbsp; <b>{x.replies}</b> replies &nbsp; <b>{x.reactions}</b> reactions</small></div><strong>{x.score.toFixed(1)}×<small> usual activity</small></strong></div>)}</Card></div>
  </main></div>
}
