export const metricInfo: Record<string, string> = {
  'Total members': 'Members on the server as of the end of the selected period. Anyone who left earlier is excluded, so this is a snapshot of the current roster rather than everyone who ever joined.',
  'New members': 'Members who joined during the selected period.',
  'Members who left': 'Members who left the server during the selected period. Leaving is a membership event, not a measure of how active someone was.',
  'Net change': 'New members minus members who left, over the selected period. This is roster growth, not activity: a community can grow while engagement falls.',
  'Active member rate': 'The share of the roster that performed at least one qualifying activity during the trailing 28 days.',
  'Active members': 'The number of unique members who performed at least one qualifying activity during the selected period.',
  'New member activation': 'The percentage of eligible new members who performed at least one qualifying activity within 7 days of joining. Eligible members have had the full 7-day activation window.',
  'Members to watch': 'Surfaces members whose engagement changed significantly, or whose current engagement state is particularly noteworthy, within the selected period.',
  'Retention': 'The percentage of members who were active in the previous 28-day period and are active again in the current one.',
  'Messages': 'The total number of member-generated messages during the selected period. Replies are messages and are included.',
  'Active days': 'The number of days in the selected period where the member sent a message, reacted, or joined a voice session, out of the days in the period.',
  'Voice sessions': 'The number of voice channel sessions the member joined during the selected period. Each join counts once.',
  'Reply rate': 'The percentage of messages that received at least one reply. A message with many replies still counts once.',
  'Reaction rate': 'The percentage of messages that received at least one reaction.',
  'Voice participants': 'The number of unique members who participated in at least one voice channel during the selected period. Each member counts once.',
  'Total voice time': 'The total elapsed time spent in voice channels during the selected period.',
  'Community strength': "A 0–100 score for the overall health of the community's social network, combining connectedness, participation, distribution and relationship quality.",
  'Connectedness': 'The percentage of members with 2 or more meaningful connections during the selected period.',
  'Participation': 'The percentage of connected members who recently interacted with an existing connection, showing whether relationships are actively maintained.',
  'Distribution': 'Whether meaningful connections are spread across the community or concentrated among a small group.',
  'Relationship quality': 'The overall strength of meaningful relationships across the community, weighted toward strong connections.',
  'Connected members': 'Members with 2 or more meaningful connections during the selected period.',
  'Weak connected members': 'Members with 0–1 meaningful connections during the selected period. This describes network position, not activity.',
  'Avg. connections per member': 'Total meaningful connections divided by all members. Each relationship is counted once.',
  'Clusters': 'Groups of members with substantially more meaningful connections within the group than outside it. Groups smaller than 5 members are not counted.',
  'Connection distribution': 'How members are distributed by their number of meaningful connections. Buckets adapt based on community size.',
  'Top influencers': 'Members ranked by Influence Score, which measures influence over the trailing 28 days from reach, relationship quality and activity.',
  'Influence score': "A 0-100 score measuring a member's influence over the trailing 28 days, matching the activity-level window, from reach, relationship quality and activity.",
  'Total links': 'The total number of meaningful member-to-member connections in the selected period. Each relationship is counted once.',
  'Bridge members': 'Members whose meaningful relationships span at least two distinct clusters.',
  'Most connected': 'Members in the top 10% by meaningful connection count.',
}